name: Guisso
description: |
  InSTEDD Guisso
version: 1.3-pre1
category: Security
maintainer: Juan Wajnerman <waj@manas.tech>
license: The MIT License
projectURL: https://www.github.com/instedd/guisso
