.catalog:
  name: Nuntium
  version: '0.2'
  description: InSTEDD Nuntium
  minimum_rancher_version: v1.5.0
  questions:
    - variable: NUNTIUM_VERSION
      label: Nuntium version
      required: true
      type: string
    - variable: SCHEME
      label: Scheme used to access this server
      required: true
      type: string
      default: https
    - variable: HOSTNAME
      label: Hostname for this server
      required: true
      type: string

    - variable: DATABASE_HOST
      label: Database Host
      required: true
      type: string
      default: db
    - variable: DATABASE_USER
      label: Database User
      required: true
      type: string
      default: root
    - variable: DATABASE_PASS
      label: Database Password
      type: password
    - variable: DATABASE_NAME
      label: Database Name
      type: string
      required: true
      default: nuntium

    - variable: GUISSO_ENABLED
      label: Use GUISSO
      required: true
      type: boolean
      default: false
    - variable: GUISSO_URL
      label: GUISSO URL
      type: string
    - variable: GUISSO_CLIENT_ID
      label: GUISSO client ID
      type: string
    - variable: GUISSO_CLIENT_SECRET
      label: GUISSO client secret
      type: password

    - variable: RABBITMQ_HOSTNAME
      label: RabbitMQ container host name
      required: true
      type: string
      default: nuntium-rabbitmq
    - variable: RABBITMQ_VOLUME
      label: Docker volume for RabbitMQ data
      required: true
      type: string
      default: nuntium-rabbitmq-data

    - variable: WEB_MEM_LIMIT
      label: Memory limit (web process)
      type: string
      required: false
      default: 512m
    - variable: WEB_MEM_RESERVATION
      label: Memory reservation (web process)
      type: string
      required: false
      default: 256m

    - variable: WORKER_MEM_LIMIT
      label: Memory limit (worker processes)
      type: string
      required: false
      default: 256m
    - variable: WORKER_MEM_RESERVATION
      label: Memory reservation (worker processes)
      type: string
      required: false
      default: 128m
