name: Nuntium
description: |
  InSTEDD Nuntium
version: 1.9.1
category: Messaging
maintainer: Juan Wajnerman <waj@manas.tech>
license: The MIT License
projectURL: https://www.github.com/instedd/nuntium
