version: '2'
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    mem_reservation: 6m
    mem_limit: 16m
    command:
      - --provider=github
      - --email-domain=*
      - --upstream=http://adminer:8080
      - --http-address=http://0.0.0.0:8080
      - --pass-basic-auth=false
      - --github-org=${GITHUB_ORG}
      {{- if .Values.GITHUB_TEAM }}
      - --github-team=${GITHUB_TEAM}
      {{- end }}
    environment:
      OAUTH2_PROXY_COOKIE_SECRET: ${COOKIE_SECRET}
      OAUTH2_PROXY_CLIENT_ID: ${GITHUB_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      OAUTH2_PROXY_SCOPE: "user:email"
    labels:
      io.rancher.container.pull_image: always
  adminer:
    image: adminer
    mem_reservation: 16m
    mem_limit: 64m
    labels:
      io.rancher.container.pull_image: always
