version: '2'
services:
  oauth2-proxy:
    image: a5huynh/oauth2_proxy
    mem_reservation: 4m
    mem_limit: 16m
    command:
      - --provider=github
      - --email-domain=*
      - --upstream=http://adminer:8080
      - --http-address=http://0.0.0.0:80
      - --pass-basic-auth=false
      - --github-org=${GITHUB_ORG}
      - --github-team=${GITHUB_TEAM}
    environment:
      OAUTH2_PROXY_COOKIE_SECRET: ${COOKIE_SECRET}
      OAUTH2_PROXY_CLIENT_ID: ${GITHUB_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    labels:
      io.rancher.container.pull_image: always
  adminer:
    image: adminer
    mem_reservation: 16m
    mem_limit: 64m
    labels:
      io.rancher.container.pull_image: always
