.catalog:
  name: Zabbix Agent
  version: '0.1'
  description: Zabbix Agent
  minimum_rancher_version: v1.5.0
  questions:
    - variable: ZBX_SERVER_HOST
      label: Zabbix Server Host
      required: true
      type: string
    - variable: ZBX_METADATA
      label: Zabbix Metadata
      type: string
    - variable: RANCHER_AGENT_HOSTNAME
      label: Rancher agent host name
      required: true
      type: string
      default: rancher-agent
    - variable: HOST_GROUP
      label: Host group where to place discovered proxy hosts
      required: true
      type: string

    - variable: PROXY_PSK_IDENTITY
      label: Proxy PSK identity
      required: true
      type: string
      default: proy
    - variable: PROXY_PSK_SECRET
      label: Proxy PSK secret name
      required: true
      type: string
