.catalog:
  name: Zabbix Agent
  version: '0.1'
  description: Zabbix Agent
  minimum_rancher_version: v1.5.0
  questions:
    - variable: ZBX_SERVER_HOST
      label: Zabbix Server Host
      required: true
      type: string
    - variable: ZBX_METADATA
      label: Zabbix Metadata
      type: string
