version: '2'
services:
  db-migrate:
    image: instedd/guisso:${GUISSO_VERSION}
    environment:
      DATABASE_URL: ${DATABASE_TYPE}://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}/${DATABASE_NAME}
    command:
    - /app/migrate
    labels:
      io.rancher.container.start_once: 'true'
  guisso:
    image: instedd/guisso:${GUISSO_VERSION}
    environment:
      DATABASE_URL: ${DATABASE_TYPE}://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}/${DATABASE_NAME}
      RAILS_CONFIG__action_mailer__smtp_settings__user_name: ${SMTP_USER}
      RAILS_CONFIG__action_mailer__smtp_settings__password: ${SMTP_PASS}
      RAILS_CONFIG__action_mailer__smtp_settings__address: ${SMTP_HOST}
      RAILS_CONFIG__action_mailer__smtp_settings__port: ${SMTP_PORT}
      DEVISE_EMAIL: ${DEVISE_EMAIL}
      SECRET_TOKEN: ${SECRET_TOKEN}
      DEVISE_SECRET_KEY: ${DEVISE_SECRET_KEY}
      COOKIE_NAME: ${COOKIE_NAME}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      {{- if .Values.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      {{- end }}
