.catalog:
  name: Guisso
  version: 1.2.1
  description: InSTEDD Guisso
  minimum_rancher_version: v1.5.0
  questions:
    - variable: DATABASE_HOST
      label: Database Host
      required: true
      type: string
      default: db
    - variable: DATABASE_USER
      label: Database User
      required: true
      type: string
      default: root
    - variable: DATABASE_PASS
      label: Database Password
      type: password
    - variable: DATABASE_NAME
      label: Database Name
      type: string
      required: true
      default: guisso

    - variable: SMTP_HOST
      label: SMTP Host
      required: true
      type: string
      default: email-smtp.us-east-1.amazonaws.com
    - variable: SMTP_USER
      label: SMTP User
      required: true
      type: string
    - variable: SMTP_PASS
      label: SMTP Password
      type: password
    - variable: SMTP_PORT
      label: SMTP Port
      type: int
      required: true
      default: 587
    - variable: DEVISE_EMAIL
      label: Devise email address
      required: true
      type: string
      default: noreply@instedd.org
