.catalog:
  name: Guisso
  version: '0.1'
  description: InSTEDD Guisso
  minimum_rancher_version: v1.5.0
  questions:
    - variable: GUISSO_VERSION
      label: Guisso version
      required: true
      type: string

    - variable: DATABASE_TYPE
      label: Database type
      required: true
      type: enum
      default: mysql2
      options:
        - mysql2
        - postgresql
    - variable: DATABASE_HOST
      label: Database Host
      required: true
      type: string
      default: db
    - variable: DATABASE_USER
      label: Database User
      required: true
      type: string
      default: root
    - variable: DATABASE_PASS
      label: Database Password
      type: password
    - variable: DATABASE_NAME
      label: Database Name
      type: string
      required: true
      default: guisso

    - variable: SMTP_HOST
      label: SMTP Host
      required: true
      type: string
      default: email-smtp.us-east-1.amazonaws.com
    - variable: SMTP_USER
      label: SMTP User
      required: true
      type: string
    - variable: SMTP_PASS
      label: SMTP Password
      type: password
    - variable: SMTP_PORT
      label: SMTP Port
      type: int
      required: true
      default: 587
    - variable: DEVISE_EMAIL
      label: Devise email address
      required: true
      type: string
      default: noreply@instedd.org

    - variable: SECRET_TOKEN
      label: Secret token
      required: true
      type: password
    - variable: DEVISE_SECRET_KEY
      label: Devise secret key
      type: password
      required: true

    - variable: GOOGLE_CLIENT_ID
      label: Google client ID
      type: string
    - variable: GOOGLE_CLIENT_SECRET
      label: Google client secret
      type: password

    - variable: COOKIE_NAME
      label: Guisso cookie name
      type: string
      required: true
      default: guisso
    - variable: COOKIE_DOMAIN
      label: Guisso cookie domain
      type: string
      required: true
      default: instedd.org

    - variable: INTERCOM_APP_ID
      label: Intercom App ID
      type: string
      required: false

    - variable: WEB_MEM_LIMIT
      label: Memory limit (web process)
      type: string
      required: false
      default: 512m

    - variable: WEB_MEM_RESERVATION
      label: Memory reservation (web process)
      type: string
      required: false
      default: 256m
