version: '2'
services:
  db-migrate:
    image: instedd/ask:${SURVEDA_VERSION}
    command: mix ecto.migrate
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_USER: ${DATABASE_USER}
      DISABLE_REPO_TIMEOUT: "true"
    {{- if .Values.APP_MEM_LIMIT }}
    mem_limit: ${APP_MEM_LIMIT}
    {{- end }}
    {{- if .Values.APP_MEM_RESERVATION }}
    mem_reservation: ${APP_MEM_RESERVATION}
    {{- end }}
    labels:
      io.rancher.container.start_once: "true"
      io.rancher.container.pull_image: always

  app:
    image: instedd/ask:${SURVEDA_VERSION}
    {{- if .Values.APP_MEM_LIMIT }}
    mem_limit: ${APP_MEM_LIMIT}
    {{- end }}
    {{- if .Values.APP_MEM_RESERVATION }}
    mem_reservation: ${APP_MEM_RESERVATION}
    {{- end }}
    environment:
      BROKER_BATCH_SIZE: ${BROKER_BATCH_SIZE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_USER: ${DATABASE_USER}
      EMAIL_FROM_EMAIL: ${EMAIL_FROM_EMAIL}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME}
      GOOGLE_URL_SHORTENER_API_KEY: ${GOOGLE_URL_SHORTENER_API_KEY}
      {{- if .Values.MOBILE_WEB_BASE_URL }}
      MOBILE_WEB_BASE_URL: ${MOBILE_WEB_BASE_URL}
      {{- end }}
      HOST: ${HOST}
      INITIAL_ELIGIBILITY_RATE: ${INITIAL_ELIGIBILITY_RATE}
      INITIAL_RESPONSE_RATE: ${INITIAL_RESPONSE_RATE}
      INITIAL_VALID_RESPONDENT_RATE: ${INITIAL_VALID_RESPONDENT_RATE}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_PUBLIC_DSN: ${SENTRY_PUBLIC_DSN}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_USER: ${SMTP_USER}
      {{- if .Values.INTERCOM_APP_ID }}
      INTERCOM_APP_ID: ${INTERCOM_APP_ID}
      {{- end }}

      {{- if eq .Values.GUISSO_ENABLED "true" }}
      GUISSO_ENABLED: 'true'
      GUISSO_BASE_URL: ${GUISSO_BASE_URL}
      GUISSO_CLIENT_ID: ${GUISSO_CLIENT_ID}
      GUISSO_CLIENT_SECRET: ${GUISSO_CLIENT_SECRET}
      {{- end }}

      {{- if contains "," .Values.NUNTIUM_APP_ID }}
      {{- $nuntiumAppIds := split "," .Values.NUNTIUM_APP_ID }}
      {{- $nuntiumBaseUrls := split "," .Values.NUNTIUM_BASE_URL }}
      {{- $nuntiumClientIds := split "," .Values.NUNTIUM_CLIENT_ID }}
      {{- $nuntiumClientSecrets := split "," .Values.NUNTIUM_CLIENT_SECRET }}
      {{- $nuntiumGuissoBaseUrls := split "," .Values.NUNTIUM_GUISSO_BASE_URL }}
      {{- $nuntiumFriendlyNames := split "," .Values.NUNTIUM_FRIENDLY_NAME }}
      {{- $nuntiumChannelUis := split "," .Values.NUNTIUM_CHANNEL_UI }}
      NUNTIUM_INSTANCES: {{ $nuntiumAppIds | len }}
      {{- range $key, $value := $nuntiumAppIds }}
      {{- $index := substr 1 -1 $key | atoi | add1 }}
      NUNTIUM_APP_ID_{{ $index }}: {{ $value | trim }}
      NUNTIUM_BASE_URL_{{ $index }}: {{ index $nuntiumBaseUrls $key | trim }}
      NUNTIUM_CLIENT_ID_{{ $index }}: {{ index $nuntiumClientIds $key | trim }}
      NUNTIUM_CLIENT_SECRET_{{ $index }}: {{ index $nuntiumClientSecrets $key | trim }}
      NUNTIUM_GUISSO_BASE_URL_{{ $index }}: {{ index $nuntiumGuissoBaseUrls $key | trim }}
      NUNTIUM_FRIENDLY_NAME_{{ $index }}: {{ index $nuntiumFriendlyNames $key | trim }}
      NUNTIUM_CHANNEL_UI_{{ $index }}: {{ index $nuntiumChannelUis $key | trim }}
      {{- end }}
      {{- else }}
      NUNTIUM_APP_ID: ${NUNTIUM_APP_ID}
      NUNTIUM_BASE_URL: ${NUNTIUM_BASE_URL}
      NUNTIUM_CLIENT_ID: ${NUNTIUM_CLIENT_ID}
      NUNTIUM_CLIENT_SECRET: ${NUNTIUM_CLIENT_SECRET}
      NUNTIUM_GUISSO_BASE_URL: ${NUNTIUM_GUISSO_BASE_URL}
      NUNTIUM_CHANNEL_UI: ${NUNTIUM_CHANNEL_UI}
      {{- end }}

      {{- if contains "," .Values.VERBOICE_APP_ID }}
      {{- $verboiceAppIds := split "," .Values.VERBOICE_APP_ID }}
      {{- $verboiceBaseUrls := split "," .Values.VERBOICE_BASE_URL }}
      {{- $verboiceClientIds := split "," .Values.VERBOICE_CLIENT_ID }}
      {{- $verboiceClientSecrets := split "," .Values.VERBOICE_CLIENT_SECRET }}
      {{- $verboiceGuissoBaseUrls := split "," .Values.VERBOICE_GUISSO_BASE_URL }}
      {{- $verboiceFriendlyNames := split "," .Values.VERBOICE_FRIENDLY_NAME }}
      {{- $verboiceChannelUis := split "," .Values.VERBOICE_CHANNEL_UI }}
      VERBOICE_INSTANCES: {{ $verboiceAppIds | len }}
      {{- range $key, $value := $verboiceAppIds }}
      {{- $index := substr 1 -1 $key | atoi | add1 }}
      VERBOICE_APP_ID_{{ $index }}: {{ $value | trim }}
      VERBOICE_BASE_URL_{{ $index }}: {{ index $verboiceBaseUrls $key | trim }}
      VERBOICE_CLIENT_ID_{{ $index }}: {{ index $verboiceClientIds $key | trim }}
      VERBOICE_CLIENT_SECRET_{{ $index }}: {{ index $verboiceClientSecrets $key | trim }}
      VERBOICE_GUISSO_BASE_URL_{{ $index }}: {{ index $verboiceGuissoBaseUrls $key | trim }}
      VERBOICE_FRIENDLY_NAME_{{ $index }}: {{ index $verboiceFriendlyNames $key | trim }}
      VERBOICE_CHANNEL_UI_{{ $index }}: {{ index $verboiceChannelUis $key | trim }}
      {{- end }}
      {{- else }}
      VERBOICE_APP_ID: ${VERBOICE_APP_ID}
      VERBOICE_BASE_URL: ${VERBOICE_BASE_URL}
      VERBOICE_CLIENT_ID: ${VERBOICE_CLIENT_ID}
      VERBOICE_CLIENT_SECRET: ${VERBOICE_CLIENT_SECRET}
      VERBOICE_GUISSO_BASE_URL: ${VERBOICE_GUISSO_BASE_URL}
      VERBOICE_CHANNEL_UI: ${VERBOICE_CHANNEL_UI}
      {{- end }}

    labels:
      io.rancher.container.pull_image: always
