version: '2'
services:
  app:
    image: instedd/ask:${SURVEDA_VERSION}
    environment:
      BROKER_BATCH_SIZE: ${BROKER_BATCH_SIZE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_USER: ${DATABASE_USER}
      EMAIL_FROM_EMAIL: ${EMAIL_FROM_EMAIL}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME}
      GOOGLE_URL_SHORTENER_API_KEY: ${GOOGLE_URL_SHORTENER_API_KEY}
      HOST: ${HOST}
      INITIAL_ELIGIBILITY_RATE: ${INITIAL_ELIGIBILITY_RATE}
      INITIAL_RESPONSE_RATE: ${INITIAL_RESPONSE_RATE}
      INITIAL_VALID_RESPONDENT_RATE: ${INITIAL_VALID_RESPONDENT_RATE}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_PUBLIC_DSN: ${SENTRY_PUBLIC_DSN}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_USER: ${SMTP_USER}
      NUNTIUM_APP_ID: ${NUNTIUM_APP_ID}
      NUNTIUM_BASE_URL: ${NUNTIUM_BASE_URL}
      NUNTIUM_CLIENT_ID: ${NUNTIUM_CLIENT_ID}
      NUNTIUM_CLIENT_SECRET: ${NUNTIUM_CLIENT_SECRET}
      NUNTIUM_GUISSO_BASE_URL: ${NUNTIUM_GUISSO_BASE_URL}
      VERBOICE_APP_ID: ${VERBOICE_APP_ID}
      VERBOICE_BASE_URL: ${VERBOICE_BASE_URL}
      VERBOICE_CLIENT_ID: ${VERBOICE_CLIENT_ID}
      VERBOICE_CLIENT_SECRET: ${VERBOICE_CLIENT_SECRET}
      VERBOICE_GUISSO_BASE_URL: ${VERBOICE_GUISSO_BASE_URL}
    command:
    - /bin/sh
    - -c
    - mix ecto.migrate && elixir --sname server -S mix phoenix.server
