version: '2'
services:
  curator:
    image: instedd/filebeat-curator
    environment:
      ES_HOST: ${ES_HOST}
      DAYS: ${DAYS}
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
      cron.schedule: '@daily'
  filebeat:
    image: instedd/filebeat-docker
    environment:
      ELASTICSEARCH_URL: https://${ES_HOST}:443
      TAIL_FILES: ${TAIL_FILES}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/containers:/var/lib/docker/containers
    - filebeat_data:/usr/share/filebeat/data
    mem_reservation: 128m
    mem_limit: 256m
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    mem_reservation: 6m
    mem_limit: 16m
    environment:
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
    command:
    - --provider=github
    - --email-domain=*
    - --upstream=https://${ES_HOST}
    - --http-address=http://0.0.0.0:8080
    - --pass-basic-auth=false
    - --github-org=${OAUTH2_PROXY_GITHUB_ORG}
    {{- if .Values.OAUTH2_PROXY_GITHUB_TEAM }}
    - --github-team=${OAUTH2_PROXY_GITHUB_TEAM}
    {{- end }}
    - --scope="user:email"
    labels:
      io.rancher.container.pull_image: always
      logging-proxy: {{ .Stack.Name }}
volumes:
  filebeat_data:
    per_container: true
