version: '2'
services:
  runtime: &runtime
    image: instedd/aida:${RUNTIME_VERSION}
    environment:
      DATABASE_URL: ecto://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}/${RUNTIME_DATABASE_NAME}
      SENTRY_DSN: ${SENTRY_DSN}
      PRIVATE_KEY: ${PRIVATE_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    labels:
      io.rancher.container.pull_image: always
    {{- if .Values.RUNTIME_MEM_LIMIT }}
    mem_limit: ${RUNTIME_MEM_LIMIT}
    {{- end }}
    {{- if .Values.RUNTIME_MEM_RESERVATION }}
    mem_reservation: ${RUNTIME_MEM_RESERVATION}
    {{- end }}
  runtime-db-migrate:
    <<: *runtime
    command: mix ecto.migrate
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: "true"
  ui: &ui
    image: instedd/aida-ui:${UI_VERSION}
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}/${UI_DATABASE_NAME}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SETTINGS__BACKEND__URL: http://runtime
      SENTRY_DSN: ${SENTRY_DSN}
      SETTINGS__BACKEND__PUBLIC_SOCKET_URL: wss://${HOSTNAME}/socket
      SETTINGS__BASE_URL: https://${HOSTNAME}
      SETTINGS__SMTP_SETTINGS__USER_NAME: ${SMTP_USER}
      SETTINGS__SMTP_SETTINGS__PASSWORD: ${SMTP_PASS}
      SETTINGS__SMTP_SETTINGS__ADDRESS: ${SMTP_HOST}
      SETTINGS__SMTP_SETTINGS__PORT: ${SMTP_PORT}
      SETTINGS__MAILER__FROM: ${EMAILS_FROM}
      GUISSO_URL: ${GUISSO_URL}
      GUISSO_CLIENT_ID: ${GUISSO_CLIENT_ID}
      GUISSO_CLIENT_SECRET: ${GUISSO_CLIENT_SECRET}
      SETTINGS__BACKEND__PUBLIC_CONTENT_URL: https://${HOSTNAME}/content
    labels:
      io.rancher.container.pull_image: always
    {{- if .Values.UI_MEM_LIMIT }}
    mem_limit: ${UI_MEM_LIMIT}
    {{- end }}
    {{- if .Values.UI_MEM_RESERVATION }}
    mem_reservation: ${UI_MEM_RESERVATION}
    {{- end }}
  ui-jobs:
    <<: *ui
    command:
      - ./bin/rake
      - jobs:work
    {{- if .Values.UI_JOBS_MEM_LIMIT }}
    mem_limit: ${UI_JOBS_MEM_LIMIT}
    {{- end }}
    {{- if .Values.UI_JOBS_MEM_RESERVATION }}
    mem_reservation: ${UI_JOBS_MEM_RESERVATION}
    {{- end }}
  ui-db-migrate:
    <<: *ui
    command:
      - /bin/sh
      - -c
      - rake db:migrate
    labels:
      io.rancher.container.start_once: "true"
      io.rancher.container.pull_image: always
  redis:
    image: redis:4
    labels:
      io.rancher.container.pull_image: always
    {{- if .Values.REDIS_MEM_LIMIT }}
    mem_limit: ${REDIS_MEM_LIMIT}
    {{- end }}
    {{- if .Values.REDIS_MEM_RESERVATION }}
    mem_reservation: ${REDIS_MEM_RESERVATION}
    {{- end }}
