version: '2'

services:
  web: &web
    image: instedd/maap-store:${MAAP_VERSION}
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASS}
      DATABASE_NAME: ${DATABASE_NAME}
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: redis://cache
    volumes:
      - ${VOLUME_APP_DATA}:/data
    labels:
      io.rancher.container.pull_image: always
    mem_reservation: ${WEB_MEM_RESERVATION}
    mem_limit: ${WEB_MEM_LIMIT}

  worker:
    <<: *app
    command: bundle exec sidekiq
    mem_reservation: ${WORKER_MEM_RESERVATION}
    mem_limit: ${WORKER_MEM_LIMIT}

  cache:
    image: redis
    volumes:
      - ${VOLUME_CACHE_DATA}:/data
    labels:
      io.rancher.container.pull_image: always
    mem_reservation: ${CACHE_MEM_RESERVATION}
    mem_limit: ${CACHE_MEM_LIMIT}
