.catalog:
  name: ResourceMap
  version: '0.1'
  description: InSTEDD ResourceMap
  minimum_rancher_version: v1.5.0
  questions:
    - variable: RESMAP_VERSION
      label: ResourceMap version
      required: true
      type: string

    - variable: HOSTNAME
      label: Host name
      required: true
      type: string

    - variable: DATABASE_HOST
      label: Database Host
      required: true
      type: string
    - variable: DATABASE_USER
      label: Database User
      required: true
      type: string
    - variable: DATABASE_PASS
      label: Database Password
      type: password
    - variable: DATABASE_NAME
      label: Database Name
      type: string
      required: true

    - variable: ELASTICSEARCH
      label: Include Elasticsearch in the stack
      type: boolean
      default: false

    - variable: ELASTICSEARCH_URL
      label: Elasticsearch Url
      required: true
      type: string

    - variable: GUISSO_ENABLED
      label: Use GUISSO
      required: true
      type: boolean
      default: true
    - variable: GUISSO_URL
      label: GUISSO URL
      type: string
      default: https://login.instedd.org
    - variable: GUISSO_CLIENT_ID
      label: GUISSO Client ID
      type: string
    - variable: GUISSO_CLIENT_SECRET
      label: GUISSO Client Secret
      type: password

    - variable: SMTP_HOST
      label: SMTP Host
      required: true
      type: string
      default: email-smtp.us-east-1.amazonaws.com
    - variable: SMTP_USER
      label: SMTP User
      required: true
      type: string
    - variable: SMTP_PASS
      label: SMTP Password
      type: password
    - variable: SMTP_PORT
      label: SMTP Port
      type: int
      required: true
      default: 587

    - variable: SECRET_KEY_BASE
      label: Secret Key Base (used to sign/encrypt session tokens)
      type: password
      required: true
    - variable: GOOGLE_MAPS_KEY
      label: Google Maps JavaScript API Key
      description: Obtain from https://developers.google.com/maps/documentation/javascript/get-api-key
      required: true
      type: string
    - variable: NEWRELIC_LICENSE_KEY
      label: New Relic License Key
      type: string

    - variable: NUNTIUM_URL
      label: Nuntium Host
      type: string
      default: http://nuntium.instedd.org
    - variable: NUNTIUM_ACCOUNT
      label: Nuntium Account
      type: string
    - variable: NUNTIUM_APPLICATION
      label: Nuntium Application
      type: string
    - variable: NUNTIUM_PASSWORD
      label: Nuntium Password
      type: string

    - variable: INTERCOM_APP_ID
      label: Intercom App ID
      type: string
      required: false

    - variable: ELASTICSEARCH_IMAGE
      label: Elasticsearch Image
      type: string
      default: elasticsearch:1.7
    - variable: ELASTICSEARCH_HEAP_SIZE
      label: Java Heap Size for Elasticsearch
      type: string
      default: 2048m
    - variable: ELASTICSEARCH_JAVA_OPTS
      label: Java Options for Elasticsearch
      type: string
      default: -Des.index.number_of_shards=1 -Des.index.number_of_replicas=0

    - variable: VOLUME_DRIVER
      label: Volume Driver
      type: string
      default: rancher-nfs
      required: true
    - variable: VOLUME_REDIS
      label: Redis Volume
      type: string
      required: true
    - variable: VOLUME_UPLOADS
      label: Uploads Volume
      type: string
      required: true
    - variable: VOLUME_IMPORT_WIZARD
      label: Import Wizard Temp Volume
      type: string
      required: true
    - variable: VOLUME_ELASTICSEARCH
      label: Elasticsearch Data Volume
      type: string
      required: false

    - variable: WEB_MEM_LIMIT
      label: Memory limit (web process)
      type: string
      required: true
      default: 512m
    - variable: WEB_MEM_RESERVATION
      label: Memory reservation (web process)
      type: string
      required: true
      default: 192m

    - variable: REDIS_MEM_LIMIT
      label: Memory limit (redis process)
      type: string
      required: true
      default: 128m
    - variable: REDIS_MEM_RESERVATION
      label: Memory reservation (redis process)
      type: string
      required: true
      default: 16m

    - variable: RESQUE_MEM_LIMIT
      label: Memory limit (resque process)
      type: string
      required: true
      default: 512m
    - variable: RESQUE_MEM_RESERVATION
      label: Memory reservation (resque process)
      type: string
      required: true
      default: 192m

    - variable: RESQUE_SCHEDULER_MEM_LIMIT
      label: Memory limit (resque scheduler process)
      type: string
      required: true
      default: 512m
    - variable: RESQUE_SCHEDULER_MEM_RESERVATION
      label: Memory reservation (resque scheduler process)
      type: string
      required: true
      default: 128m

    - variable: ELASTICSEARCH_MEM_LIMIT
      label: Memory limit (elasticsearch process)
      type: string
      required: true
      default: 3g
    - variable: ELASTICSEARCH_MEM_RESERVATION
      label: Memory reservation (elasticsearch process)
      type: string
      required: true
      default: 2g
