version: '2'
services:
  mem-limit:
    image: instedd/rancher-memory-limiter
    volumes:
    - /sys:/host-sys
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
